services:
  iaeditais_db:
    image: pgvector/pgvector:pg17
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: iaeditais
      POSTGRES_PASSWORD: postgres
      TZ: America/Sao_Paulo
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "${PORT_DB:-5432}:5432"

  iaeditais_api:
    image: gleidsoncosta/fiotec-iaeditais:latest
    entrypoint: ./entrypoint.sh
    ports:
      - "${PORT_API:-8000}:8000"
    environment:
      OTEL_SERVICE_NAME: iaEditais
      OTEL_EXPORTER_OTLP_ENDPOINT: iaeditais_otel:4317
      OTEL_EXPORTER_OTLP_INSECURE: true
      OTEL_PYTHON_LOG_LEVEL: info
      OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: true
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      CACHE_URL: 'redis://iaeditais_redis:6379/0'
      DATABASE_URL: postgresql+psycopg://postgres:postgres@iaeditais_db:5432/iaeditais
      TZ: America/Sao_Paulo
    env_file: ".env"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - storage:/app/iaEditais/storage
    depends_on:
      iaeditais_db:
        condition: service_healthy
      iaeditais_redis:
        condition: service_healthy

  iaeditais_redis:
    image: redis:latest
    ports:
      - "${PORT_REDIS:-6379}:6379"
    volumes:
      - cache:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  iaeditais_otel:
    image: grafana/otel-lgtm
    profiles: [ "prod" ]
    ports:
      - "${PORT_OTEL_GRAFANA:-3000}:3000"
      - "${PORT_OTEL_1:-4317}:4317"
      - "${PORT_OTEL_2:-4318}:4318"
    volumes:
      - lgtm_data:/data

  evolution_api:
    image: gleidsoncosta/evolution-api:v2.3.6
    ports:
      - "${PORT_EVO:-8082}:8080"
    env_file:
      - .evolution.env
    volumes:
      - evolution_instances:/evolution/instances
    depends_on:
      iaeditais_db:
        condition: service_healthy

volumes:
  dbdata:
  storage:
  cache:
  evolution_instances:
  lgtm_data:
