"""Referências dos documentos

Revision ID: e92898cdeacb
Revises: 0005
Create Date: 2026-08-13 17:59:25.732001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e92898cdeacb'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('documents_bundle_id_fkey'), 'documents', type_='foreignkey')
    op.drop_column('documents', 'bundle_id')
    op.drop_table('bundle_document_typifications')
    op.drop_table('bundle_documents')
    op.drop_table('bundles')
    op.create_foreign_key('fk_chat_conversations_deleted_by', 'chat_conversations', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_chat_conversations_updated_by', 'chat_conversations', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_chat_conversations_created_by', 'chat_conversations', 'users', ['created_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_document_group_items_created_by', 'document_group_items', 'users', ['created_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_document_group_items_deleted_by', 'document_group_items', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_document_group_items_updated_by', 'document_group_items', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_document_groups_updated_by', 'document_groups', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_document_groups_deleted_by', 'document_groups', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_document_groups_created_by', 'document_groups', 'users', ['created_by'], ['id'], use_alter=True)
    op.add_column('document_messages', sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key('fk_project_documents_updated_by', 'project_documents', 'users', ['updated_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_project_documents_created_by', 'project_documents', 'users', ['created_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_project_documents_deleted_by', 'project_documents', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_projects_created_by', 'projects', 'users', ['created_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_projects_deleted_by', 'projects', 'users', ['deleted_by'], ['id'], use_alter=True)
    op.create_foreign_key('fk_projects_updated_by', 'projects', 'users', ['updated_by'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_projects_updated_by', 'projects', type_='foreignkey')
    op.drop_constraint('fk_projects_deleted_by', 'projects', type_='foreignkey')
    op.drop_constraint('fk_projects_created_by', 'projects', type_='foreignkey')
    op.drop_constraint('fk_project_documents_deleted_by', 'project_documents', type_='foreignkey')
    op.drop_constraint('fk_project_documents_created_by', 'project_documents', type_='foreignkey')
    op.drop_constraint('fk_project_documents_updated_by', 'project_documents', type_='foreignkey')
    op.create_table('bundles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_bundles_created_by')),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_bundles_deleted_by')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_bundles_updated_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('bundles_pkey'))
    )
    op.add_column('documents', sa.Column('bundle_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('documents_bundle_id_fkey'), 'documents', 'bundles', ['bundle_id'], ['id'])
    op.drop_column('document_messages', 'references')
    op.drop_constraint('fk_document_groups_created_by', 'document_groups', type_='foreignkey')
    op.drop_constraint('fk_document_groups_deleted_by', 'document_groups', type_='foreignkey')
    op.drop_constraint('fk_document_groups_updated_by', 'document_groups', type_='foreignkey')
    op.drop_constraint('fk_document_group_items_updated_by', 'document_group_items', type_='foreignkey')
    op.drop_constraint('fk_document_group_items_deleted_by', 'document_group_items', type_='foreignkey')
    op.drop_constraint('fk_document_group_items_created_by', 'document_group_items', type_='foreignkey')
    op.drop_constraint('fk_chat_conversations_created_by', 'chat_conversations', type_='foreignkey')
    op.drop_constraint('fk_chat_conversations_updated_by', 'chat_conversations', type_='foreignkey')
    op.drop_constraint('fk_chat_conversations_deleted_by', 'chat_conversations', type_='foreignkey')
    op.create_table('bundle_documents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bundle_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], name=op.f('bundle_documents_bundle_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_bundle_documents_created_by')),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_bundle_documents_deleted_by')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_bundle_documents_updated_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('bundle_documents_pkey'))
    )
    op.create_table('bundle_document_typifications',
    sa.Column('bundle_document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('typification_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bundle_document_id'], ['bundle_documents.id'], name=op.f('bundle_document_typifications_bundle_document_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_bundle_document_created_by')),
    sa.ForeignKeyConstraint(['typification_id'], ['typifications.id'], name=op.f('bundle_document_typifications_typification_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bundle_document_id', 'typification_id', name=op.f('bundle_document_typifications_pkey'))
    )
    # ### end Alembic commands ###
