name: CI/CD Pipeline - iaEditais Back

on:
  push:
    branches: ["support/v3.x"]

env:
  IMAGE_NAME: gleidsoncosta/fiotec-iaeditais
  DATABASE_URL: postgresql+psycopg://postgres:postgres@iaeditais_db:5432/iaeditais

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Instalar Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Instalar Dependências
        run: poetry install --no-interaction --no-root

      - name: Rodar Testes
        run: poetry run task test

  build-and-push:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euo pipefail

            cd /home/${{ secrets.USERNAME }}/apps/develop/iaEditais-back

            git pull --ff-only

            docker compose pull iaeditais_api
            docker compose up -d --force-recreate iaeditais_api

            echo "Limpando imagens não utilizadas..."
            docker image prune -af
            docker builder prune -af

            docker compose ps
